# Generated by Django 4.0.2 on 2022-07-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name_alter_user_header_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
