# Generated by Django 4.0.2 on 2022-03-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_relationship_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_header',
            field=models.URLField(default='https://st.depositphotos.com/2218212/2938/i/450/depositphotos_29387653-stock-photo-facebook-profile.jpg'),
        ),
    ]
