<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-07-14 19:04
=======
# Generated by Django 4.0.2 on 2022-04-08 06:24
>>>>>>> 78e8157e87090d617eb91c9d38cd1e4995547a86

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
<<<<<<< HEAD
                ('content', models.CharField(max_length=280)),
=======
                ('content', models.TextField()),
>>>>>>> 78e8157e87090d617eb91c9d38cd1e4995547a86
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
